controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: ''
        es: '/es'
        nl: '/nl'
        fr: '/fr'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
